// authentificacion
export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

// common
export const THINGS_FETCH_BEGIN = "THINGS_FETCH_BEGIN";
export const THINGS_FETCH_SUCCESS = "THINGS_FETCH_SUCCESS";
export const THINGS_FETCH_FAILURE = "THINGS_FETCH_FAILURE";

// defects
export const FETCH_DEFECTS_BEGIN = "FETCH_DEFECTS_BEGIN";
export const FETCH_DEFECTS_SUCCESS = "FETCH_DEFECTS_SUCCESS";
export const FETCH_DEFECTS_FAILURE = "FETCH_DEFECTS_FAILURE";

export const INVALIDATE_DEFECTS = "INVALIDATE_DEFECTS";

export const DEFECTS_DELETE_LOCAL = "DEFECTS_DELETE_LOCAL";
export const DEFECTS_UPDATE_LOCAL = "DEFECTS_UPDATE_LOCAL";
export const DEFECT_INSERT_BEGIN = "DEFECT_INSERT_BEGIN";
export const DEFECT_UPDATE_BEGIN = "DEFECT_UPDATE_BEGIN";
export const DEFECT_DELETE_BEGIN = "DEFECT_DELETE_BEGIN";
export const DEFECT_INSERT_SUCCESS = "DEFECT_INSERT_SUCCESS";
export const DEFECT_UPDATE_SUCCESS = "DEFECT_UPDATE_SUCCESS";
export const DEFECT_DELETE_SUCCESS = "DEFECT_DELETE_SUCCESS";
export const DEFECT_INSERT_FAILURE = "DEFECT_INSERT_FAILURE";
export const DEFECT_UPDATE_FAILURE = "DEFECT_UPDATE_FAILURE";
export const DEFECT_DELETE_FAILURE = "DEFECT_DELETE_FAILURE";

export const DEFECTS_PAGE_CHANGE = "DEFECTS_PAGE_CHANGE";
export const DEFECTS_PER_PAGE_CHANGE = "DEFECTS_PER_PAGE_CHANGE";
export const DEFECT_TOGGLE_FS = "DEFECT_TOGGLE_FS";
export const DEFECT_TOGGLE_FS_MANUAL = "DEFECT_TOGGLE_FS_MANUAL";
export const DEFECTS_FILTERSORT_APPLIED = "DEFECTS_FILTERSORT_APPLIED";
export const DEFECTS_FILTERSORT_APPLY_ERROR = "DEFECTS_FILTERSORT_APPLY_ERROR";
export const DEFECTS_REFRESH = "DEFECTS_REFRESH";
export const HIDE_DEFECTS_WARNING = "HIDE_DEFECTS_WARNING";
export const HIDE_DEFECTS_ERROR = "HIDE_DEFECTS_ERROR";
export const DEFECTS_SET_WARNING = "DEFECTS_SET_WARNING";
export const HIDE_DEFECTS_SUCCESS = "HIDE_DEFECTS_SUCCESS";
export const DEFECTS_SET_SUCCESS = "DEFECTS_SET_SUCCESS";

// weldings
export const FETCH_WELDINGS_BEGIN = "FETCH_WELDINGS_BEGIN";
export const FETCH_WELDINGS_SUCCESS = "FETCH_WELDINGS_SUCCESS";
export const FETCH_WELDINGS_FAILURE = "FETCH_WELDINGS_FAILURE";

export const INVALIDATE_WELDINGS = "INVALIDATE_WELDINGS";

export const WELDINGS_DELETE_LOCAL = "WELDINGS_DELETE_LOCAL";
export const WELDINGS_UPDATE_LOCAL = "WELDINGS_UPDATE_LOCAL";
export const WELDING_INSERT_BEGIN = "WELDING_INSERT_BEGIN";
export const WELDING_UPDATE_BEGIN = "WELDING_UPDATE_BEGIN";
export const WELDING_DELETE_BEGIN = "WELDING_DELETE_BEGIN";
export const WELDING_INSERT_SUCCESS = "WELDING_INSERT_SUCCESS";
export const WELDING_UPDATE_SUCCESS = "WELDING_UPDATE_SUCCESS";
export const WELDING_DELETE_SUCCESS = "WELDING_DELETE_SUCCESS";
export const WELDING_INSERT_FAILURE = "WELDING_INSERT_FAILURE";
export const WELDING_UPDATE_FAILURE = "WELDING_UPDATE_FAILURE";
export const WELDING_DELETE_FAILURE = "WELDING_DELETE_FAILURE";

export const WELDINGS_PAGE_CHANGE = "WELDINGS_PAGE_CHANGE";
export const WELDINGS_PER_PAGE_CHANGE = "WELDINGS_PER_PAGE_CHANGE";
export const WELDING_TOGGLE_FS = "WELDING_TOGGLE_FS";
export const WELDING_TOGGLE_FS_MANUAL = "WELDING_TOGGLE_FS_MANUAL";
export const WELDINGS_FILTERSORT_APPLIED = "WELDINGS_FILTERSORT_APPLIED";
export const WELDINGS_FILTERSORT_APPLY_ERROR = "WELDINGS_FILTERSORT_APPLY_ERROR";


// fs queries
export const QUERIES_FETCH_BEGIN = "QUERIES_FETCH_BEGIN";
export const QUERIES_FETCH_SUCCESS = "QUERIES_FETCH_SUCCESS";
export const QUERIES_FETCH_FAILURE = "QUERIES_FETCH_FAILURE";
export const QUERIES_UPDATE_BEGIN = "QUERIES_UPDATE_BEGIN";
export const QUERIES_UPDATE_SUCCESS = "QUERIES_UPDATE_SUCCESS";
export const QUERIES_UPDATE_FAILURE = "QUERIES_UPDATE_FAILURE";
