// authentificacion
export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

// common
export const THINGS_FETCH_BEGIN = "THINGS_FETCH_BEGIN";
export const THINGS_FETCH_SUCCESS = "THINGS_FETCH_SUCCESS";
export const THINGS_FETCH_FAILURE = "THINGS_FETCH_FAILURE";

// items
export const ITEMS_FETCH_BEGIN = "ITEMS_FETCH_BEGIN";
export const ITEMS_FETCH_SUCCESS = "ITEMS_FETCH_SUCCESS";
export const ITEMS_FETCH_FAILURE = "ITEMS_FETCH_FAILURE";

export const ITEMS_INVALIDATE = "ITEMS_INVALIDATE";

export const ITEMS_DELETE_LOCAL = "ITEMS_DELETE_LOCAL";
export const ITEMS_UPDATE_LOCAL = "ITEMS_UPDATE_LOCAL";

export const ITEM_INSERT_BEGIN = "ITEM_INSERT_BEGIN";
export const ITEM_UPDATE_BEGIN = "ITEM_UPDATE_BEGIN";
export const ITEM_DELETE_BEGIN = "ITEM_DELETE_BEGIN";

export const ITEM_INSERT_SUCCESS = "ITEM_INSERT_SUCCESS";
export const ITEM_UPDATE_SUCCESS = "ITEM_UPDATE_SUCCESS";
export const ITEM_DELETE_SUCCESS = "ITEM_DELETE_SUCCESS";

export const ITEM_INSERT_FAILURE = "ITEM_INSERT_FAILURE";
export const ITEM_UPDATE_FAILURE = "ITEM_UPDATE_FAILURE";
export const ITEM_INSERT_FAILURE_NO_RETRY = "ITEM_INSERT_FAILURE_NO_RETRY";
export const ITEM_UPDATE_FAILURE_NO_RETRY = "ITEM_UPDATE_FAILURE_NO_RETRY";
export const ITEM_DELETE_FAILURE = "ITEM_DELETE_FAILURE";

export const ITEMS_PAGE_CHANGE = "ITEMS_PAGE_CHANGE";
export const ITEMS_PER_PAGE_CHANGE = "ITEMS_PER_PAGE_CHANGE";
export const ITEM_TOGGLE_FS = "ITEM_TOGGLE_FS";
export const ITEM_TOGGLE_FS_MANUAL = "ITEM_TOGGLE_FS_MANUAL";
export const ITEMS_FILTERSORT_APPLIED = "ITEMS_FILTERSORT_APPLIED";
export const ITEMS_FILTERSORT_APPLY_ERROR = "ITEMS_FILTERSORT_APPLY_ERROR";
export const ITEMS_REFRESH = "ITEMS_REFRESH";

export const ITEM_LIST_SET_ALERT = "ITEM_LIST_SET_ALERT";
export const ITEM_LIST_HIDE_ALERT = "ITEM_LIST_HIDE_ALERT";

export const ITEM_EDIT_SET_ALERT = "ITEM_EDIT_SET_ALERT";
export const ITEM_EDIT_HIDE_ALERT = "ITEM_EDIT_HIDE_ALERT";

// item journal
export const JOURNAL_FETCH_BEGIN = "JOURNAL_FETCH_BEGIN";
export const JOURNAL_FETCH_SUCCESS = "JOURNAL_FETCH_SUCCESS";
export const JOURNAL_FETCH_FAILURE = "JOURNAL_FETCH_FAILURE";
export const JOURNAL_REMOVE = "JOURNAL_REMOVE";
export const JOURNAL_SET = "JOURNAL_SET";


// fs queries
export const QUERIES_FETCH_BEGIN = "QUERIES_FETCH_BEGIN";
export const QUERIES_FETCH_SUCCESS = "QUERIES_FETCH_SUCCESS";
export const QUERIES_FETCH_FAILURE = "QUERIES_FETCH_FAILURE";
export const QUERY_UPDATE_BEGIN = "QUERY_UPDATE_BEGIN";
export const QUERY_UPDATE_SUCCESS = "QUERY_UPDATE_SUCCESS";
export const QUERY_UPDATE_FAILURE = "QUERY_UPDATE_FAILURE";
export const QUERY_INSERT_BEGIN = "QUERY_INSERT_BEGIN";
export const QUERY_INSERT_SUCCESS = "QUERY_INSERT_SUCCESS";
export const QUERY_INSERT_FAILURE = "QUERY_INSERT_FAILURE";
export const QUERY_DELETE_BEGIN = "QUERY_DELETE_BEGIN";
export const QUERY_DELETE_SUCCESS = "QUERY_DELETE_SUCCESS";
export const QUERY_DELETE_FAILURE = "QUERY_DELETE_FAILURE";

export const QUERIES_HIDE_WARNING = "QUERIES_HIDE_WARNING";
export const QUERIES_HIDE_ERROR = "QUERIES_HIDE_ERROR";
export const QUERIES_HIDE_SUCCESS = "QUERIES_HIDE_SUCCESS";

// current item
export const CURRENT_ITEM_SET_TYPE = "CURRENT_ITEM_SET_TYPE";

// report
export const REPORT_BEGIN = "REPORT_BEGIN";
export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const REPORT_ERROR = "REPORT_ERROR";
export const REPORT_ERASE = "REPORT_ERASE";

// operinput
export const OPERINPUT_FETCH_BEGIN = "OPERINPUT_FETCH_BEGIN";
export const OPERINPUT_FETCH_SUCCESS = "OPERINPUT_FETCH_SUCCESS";
export const OPERINPUT_FETCH_FAILURE = "OPERINPUT_FETCH_FAILURE";
export const OPERINPUT_SUPPLY_BEGIN = "OPERINPUT_SUPPLY_BEGIN";
export const OPERINPUT_SUPPLY_SUCCESS = "OPERINPUT_SUPPLY_SUCCESS";
export const OPERINPUT_SUPPLY_FAILURE = "OPERINPUT_SUPPLY_FAILURE";
export const OPERINPUT_INSERT_BEGIN = "OPERINPUT_INSERT_BEGIN";
export const OPERINPUT_INSERT_SUCCESS = "OPERINPUT_INSERT_SUCCESS";
export const OPERINPUT_INSERT_FAILURE = "OPERINPUT_INSERT_FAILURE";
export const OPERINPUT_CLEAR = "OPERINPUT_CLEAR";
export const OPERINPUT_ITEMS_SEARCH_BEGIN = "OPERINPUT_ITEMS_SEARCH_BEGIN";
export const OPERINPUT_ITEMS_SEARCH_SUCCESS = "OPERINPUT_ITEMS_SEARCH_SUCCESS";
export const OPERINPUT_ITEMS_SEARCH_FAILURE = "OPERINPUT_ITEMS_SEARCH_FAILURE";
export const OPERINPUT_DELETE_WE_BEGIN = "OPERINPUT_DELETE_WE_BEGIN";
export const OPERINPUT_DELETE_WE_SUCCESS = "OPERINPUT_DELETE_WE_SUCCESS";
export const OPERINPUT_DELETE_WE_FAILURE = "OPERINPUT_DELETE_WE_FAILURE";
export const OPERINPUT_FETCH_WE_BEGIN = "OPERINPUT_FETCH_WE_BEGIN";
export const OPERINPUT_FETCH_WE_SUCCESS = "OPERINPUT_FETCH_WE_SUCCESS";
export const OPERINPUT_FETCH_WE_FAILURE = "OPERINPUT_FETCH_WE_FAILURE";
export const OPERINPUT_WE_CLEAR = "OPERINPUT_WE_CLEAR";
export const OPERINPUT_INFO_REMOVE = "OPERINPUT_INFO_REMOVE";
export const OPERINPUT_SEARCH_INFO_REMOVE = "OPERINPUT_SEARCH_INFO_REMOVE";
export const OPERINPUT_SET_ITEMS = "OPERINPUT_SET_ITEMS";