module.exports = {
  id: {type: 'integer', label: "id"}, // insert - generates automatically, update - if wrong doesnt find
  v: {type: 'integer', label: "versija"}, // insert - generates automatically, update - if wrong doesnt update or updates the item which has been updated by someone other
  id1: {type: 'integer', validator: "isNegative", label: "ID1"},
  regbit: {type: 'integer', required: true, validator: "isNegative", label: "regiono bitas"},  
  meistrija: {type: 'string', required: true, validator: "isEmptyString", label: "meistrija"},
  linija: {type: 'string', required: true, validator: "isEmptyString", label: "linija"},
  kelias: {type: 'string', required: true, validator: "isEmptyString", label: "kelias"},
  km: {type: 'integer', required: true, validator: "isNegative", label: "km"},
  pk: {type: 'integer', required: true, validator: "isNegative", label: "pk"},
  m: {type: 'integer', required: true, validator: "isNegative", label: "m"},
  siule: {type: 'string', label: "siūlė"},
  kodas: {type: 'string', required: true, validator: "isEmptyString", label: "defekto kodas"},
  dl: {type: 'number', validator: "isNegative", label: "defekto dydis L"},
  dh: {type: 'number', validator: "isNegative", label: "defekto dydis H"},
  pavoj: {type: 'string', required: true, validator: "isEmptyString", label: "pavojingumo laipsnis"},
  kkateg: {type: 'string', required: true, validator: "isEmptyString", label: "kelio kategorija"},
  btipas: {type: 'string', required: true, validator: "isEmptyString", label: "bėgio tipas"},
  bgamykl: {type: 'string', required: true, validator: "isEmptyString", label: "bėgio gamykla"},
  bmetai: {type: 'integer', required: true, validator: "isNotYear", label: "bėgio pagaminimo metai"},
  oper: {type: 'string', required: true, validator: "isEmptyString", label: "operatoriaus kodas"},
  apar: {type: 'string', required: true, validator: "isEmptyString", label: "defektoskopo kodas"},
  daptik: {type: 'string', required: true, validator: "isNotShortDate", label: "aptikimo data"},
  dtermin: {type: 'string', validator: "isNeitherEmptyStringNorShortDate", label: "pašalinimo terminas"},
  daction: {type: 'string', validator: "isNeitherEmptyStringNorShortDate", label: "pašalinimo data"},
  action: {type: 'integer', validator: "outOfLimits", params: {min: 0, max: 2}, label: "pašalinimo būdas"},
  note: {type: 'string', validator: "wrongLength", params: {min: 0, max: 255}, label: "pastaba"},
};