import {
  FETCH_DEFECTS_BEGIN,
  DEFECT_INSERT_BEGIN,
  DEFECT_UPDATE_BEGIN,
  DEFECT_DELETE_BEGIN,
  FETCH_DEFECTS_SUCCESS,
  DEFECT_INSERT_SUCCESS,
  DEFECT_UPDATE_SUCCESS,
  DEFECT_DELETE_SUCCESS,
  DEFECT_DELETE_NOT_FOUND,
  FETCH_DEFECTS_FAILURE,
  DEFECT_INSERT_FAILURE,
  DEFECT_UPDATE_FAILURE,
  DEFECT_DELETE_FAILURE,
  LOGIN_BEGIN,
  REGISTER_BEGIN,
  THINGS_FETCH_BEGIN,
  QUERIES_FETCH_BEGIN,
  QUERIES_UPDATE_BEGIN,
  SET_CURRENT_USER,
  REGISTER_SUCCESS,
  THINGS_FETCH_SUCCESS,
  QUERIES_FETCH_SUCCESS,
  QUERIES_UPDATE_SUCCESS,
  LOGIN_ERROR,
  REGISTER_ERROR,
  THINGS_FETCH_FAILURE,
  QUERIES_FETCH_FAILURE,
  QUERIES_UPDATE_FAILURE,
  LOGOUT
} from "../actions/types";
const initialState = { isLoading: false };

export default function loadingReducer(state = initialState, action) {
  switch (action.type) {
    case FETCH_DEFECTS_BEGIN:
    case DEFECT_INSERT_BEGIN:
    case DEFECT_UPDATE_BEGIN:
    case DEFECT_DELETE_BEGIN:
    case LOGIN_BEGIN:
    case REGISTER_BEGIN:
    case THINGS_FETCH_BEGIN:
    case QUERIES_FETCH_BEGIN:
    case QUERIES_UPDATE_BEGIN:
      return {
        ...state,
        isLoading: true
      };

    case FETCH_DEFECTS_SUCCESS:
    case DEFECT_INSERT_SUCCESS:
    case DEFECT_UPDATE_SUCCESS:
    case DEFECT_DELETE_SUCCESS:
    case DEFECT_DELETE_NOT_FOUND:
    case FETCH_DEFECTS_FAILURE:
    case DEFECT_INSERT_FAILURE:
    case DEFECT_UPDATE_FAILURE:
    case DEFECT_DELETE_FAILURE:
    case SET_CURRENT_USER:
    case REGISTER_SUCCESS:
    case THINGS_FETCH_SUCCESS:
    case QUERIES_FETCH_SUCCESS:
    case QUERIES_UPDATE_SUCCESS:
    case LOGIN_ERROR:
    case REGISTER_ERROR:
    case THINGS_FETCH_FAILURE:
    case QUERIES_FETCH_FAILURE:
    case QUERIES_UPDATE_FAILURE:
      return {
        ...state,
        isLoading: false
      };

    case LOGOUT:
      return initialState;

    default:
      return state;
  }
}
