import {
  // atrodo, HISTORY nebereikia
  FETCH_DEFECTS_BEGIN,
  DEFECT_INSERT_BEGIN,
  DEFECT_UPDATE_BEGIN,
  DEFECT_DELETE_BEGIN,
  INSERT_DEFECT_HISTORY_BEGIN,
  UPDATE_DEFECT_HISTORY_BEGIN,
  DELETE_DEFECT_HISTORY_BEGIN,
  FETCH_DEFECTS_SUCCESS,
  DEFECT_INSERT_SUCCESS,
  DEFECT_UPDATE_SUCCESS,
  DEFECT_DELETE_SUCCESS,
  DEFECT_DELETE_NOT_FOUND,
  FETCH_DEFECTS_FAILURE,
  DEFECT_INSERT_FAILURE,
  DEFECT_UPDATE_FAILURE,
  DEFECT_DELETE_FAILURE,
  INSERT_DEFECT_HISTORY_SUCCESS,
  UPDATE_DEFECT_HISTORY_SUCCESS,
  DELETE_DEFECT_HISTORY_SUCCESS,
  INSERT_DEFECT_HISTORY_FAILURE,
  UPDATE_DEFECT_HISTORY_FAILURE,
  DELETE_DEFECT_HISTORY_FAILURE,
  CANCEL_CREATE_DEFECT,
  CANCEL_EDIT_DEFECT,
  CANCEL_REMOVE_DEFECT,
  CANCEL_CREATE_DEFECT_HISTORY,
  CANCEL_EDIT_DEFECT_HISTORY,
  CANCEL_REMOVE_DEFECT_HISTORY,
  LOGOUT
} from "../../actions/types";
const initialState = { isBusy: false };

export default function defectsStatusReducer(state = initialState, action) {
  switch (action.type) {
    case FETCH_DEFECTS_BEGIN:
    case DEFECT_INSERT_BEGIN:
    case DEFECT_UPDATE_BEGIN:
    case DEFECT_DELETE_BEGIN:
    case INSERT_DEFECT_HISTORY_BEGIN:
    case UPDATE_DEFECT_HISTORY_BEGIN:
    case DELETE_DEFECT_HISTORY_BEGIN:
      return {
        ...state,
        isBusy: true
      };

    case FETCH_DEFECTS_SUCCESS:
    case DEFECT_INSERT_SUCCESS:
    case DEFECT_UPDATE_SUCCESS:
    case DEFECT_DELETE_SUCCESS:
    case DEFECT_DELETE_NOT_FOUND:
    case FETCH_DEFECTS_FAILURE:
    case DEFECT_INSERT_FAILURE:
    case DEFECT_UPDATE_FAILURE:
    case DEFECT_DELETE_FAILURE:
    case INSERT_DEFECT_HISTORY_SUCCESS:
    case UPDATE_DEFECT_HISTORY_SUCCESS:
    case DELETE_DEFECT_HISTORY_SUCCESS:
    case INSERT_DEFECT_HISTORY_FAILURE:
    case UPDATE_DEFECT_HISTORY_FAILURE:
    case DELETE_DEFECT_HISTORY_FAILURE:
    case CANCEL_CREATE_DEFECT:
    case CANCEL_EDIT_DEFECT:
    case CANCEL_REMOVE_DEFECT:
    case CANCEL_CREATE_DEFECT_HISTORY:
    case CANCEL_EDIT_DEFECT_HISTORY:
    case CANCEL_REMOVE_DEFECT_HISTORY:
      return {
        ...state,
        isBusy: false
      };

    case LOGOUT:
      return {...initialState};

    default:
      return state;
  }
}
