module.exports = {
  id: {type: 'integer'}, // insert - generates automatically, update - if wrong doesnt find
  oldId: {type: 'string'},
  regbit: {type: 'integer', required: true, validator: "isNegative"}, 
  linija: {type: 'string', required: true, validator: "isEmptyString"},
  kelias: {type: 'string', required: true, validator: "isEmptyString"},
  km: {type: 'integer', required: true, validator: "isNegative"},
  pk: {type: 'integer', required: true, validator: "isNegative"},
  m: {type: 'integer', required: true, validator: "isNegative"},
  siule: {type: 'string'},
  vbudas: {type: 'string', required: true, validator: "isEmptyString"},
  virino: {type: 'string', required: true, validator: "isEmptyString"},
  data0: {type: 'string', required: true, validator: "isNotShortDate"},
  data1: {type: 'string', validator: "isNeitherEmptyStringNorShortDate"},
  oper1: {type: 'string'},
  apar1: {type: 'string'},
  data2: {type: 'string', validator: "isNeitherEmptyStringNorShortDate"},
  oper2: {type: 'string'},
  apar2: {type: 'string'},
  data3: {type: 'string', validator: "isNeitherEmptyStringNorShortDate"},
  oper3: {type: 'string'},
  apar3: {type: 'string'},
  data4: {type: 'string', validator: "isNeitherEmptyStringNorShortDate"},
  oper4: {type: 'string'},
  apar4: {type: 'string'},
  status: {type: 'integer'},
  note: {type: 'string'},
};